SELECT price * quantity AS total FROM items;
SELECT a + b - c FROM t;
SELECT a / b FROM t;
SELECT first_name || ' ' || last_name AS full_name FROM users;
SELECT -amount FROM transactions;
SELECT +balance FROM accounts;
SELECT COUNT(*) FROM orders;
SELECT COUNT(DISTINCT status) FROM orders;
SELECT SUM(amount), AVG(price), MIN(id), MAX(id) FROM orders;
SELECT UPPER(name), LOWER(email) FROM users;
SELECT COALESCE(name, 'unknown') FROM users;
SELECT NULLIF(status, 'inactive') FROM users;
SELECT my_func(a, b) FROM t;
SELECT schema1.pkg.my_func(x) FROM t;
SELECT CASE status WHEN 'A' THEN 'Active' WHEN 'I' THEN 'Inactive' ELSE 'Unknown' END FROM users;
SELECT CASE WHEN age >= 18 THEN 'Adult' WHEN age >= 13 THEN 'Teen' ELSE 'Child' END FROM users;
SELECT CAST(price AS DECIMAL(10, 2)) FROM products;
SELECT CAST(id AS VARCHAR(50)) FROM users;
SELECT (1 + 2) * 3 FROM t;
SELECT users.name FROM users;
SELECT myschema.users.name FROM myschema.users;
SELECT t.* FROM users t;
